/**
 * macOS Desktop Mode Installer
 * 
 * Creates and manages macOS integrations:
 * - Quick Action for "Send to Ronin" in Finder
 * - LaunchAgent for auto-starting Ronin Desktop Mode
 * - Folder watcher configuration
 */

import { existsSync, mkdirSync, writeFileSync, unlinkSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { execSync } from "child_process";

interface InstallerOptions {
  bridgePort?: number;
  shortcutKey?: string;
  folders?: string[];
  notifications?: boolean;
  clipboard?: boolean;
}

interface InstallationStatus {
  quickActionInstalled: boolean;
  launchAgentInstalled: boolean;
  desktopModeEnabled: boolean;
  bridgePort: number;
}

const DEFAULTS = {
  bridgePort: 17341,
  shortcutKey: "r",
  folders: ["~/Desktop", "~/Downloads"],
};

const DAEMON_PLIST_PATH = join(homedir(), "Library", "LaunchAgents", "com.ronin.daemon.plist");
const DAEMON_LOG_PATH = join(homedir(), ".ronin", "daemon.log");

/**
 * Generate AppleScript for Quick Action
 */
function generateQuickActionScript(port: number): string {
  return `-- AppleScript for "Send to Ronin" Quick Action
-- Generated by Ronin Desktop Mode Installer

on run {input, parameters}
	set filePaths to {}
	repeat with currentFile in input
		set end of filePaths to POSIX path of currentFile
	end repeat
	
	-- Send to Ronin OS Bridge
	try
		set jsonPayload to "{\"event\":\"os.file.selected\",\"data\":{\"path\":\"" & (item 1 of filePaths) & "\",\"multi\":false,"
		
		if (count of filePaths) > 1 then
			set jsonPayload to jsonPayload & "\"paths\":["
			repeat with i from 1 to count of filePaths
				if i > 1 then set jsonPayload to jsonPayload & ","
				set jsonPayload to jsonPayload & "\"" & (item i of filePaths) & "\""
			end repeat
			set jsonPayload to jsonPayload & "]"
		end if
		
		set jsonPayload to jsonPayload & "}}"
		
		-- Send HTTP request to Ronin OS Bridge
		do shell script "curl -X POST http://localhost:${port}/api/os-bridge/events \\
			-H 'Content-Type: application/json' \\
			-d '" & jsonPayload & "'"
		
		display notification "Sent to Ronin" with title "Ronin Desktop" subtitle ((count of filePaths) as string) & " file(s)"
		
	on error errMsg
		display notification errMsg with title "Ronin Desktop" subtitle "Error sending files"
	end try
	
	return input
end run`;
}

/**
 * Generate LaunchAgent plist
 */
function generateLaunchAgentPlist(
  roninPath: string,
  configPath: string
): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>ai.ronin.desktop</string>
    <key>ProgramArguments</key>
    <array>
        <string>${roninPath}</string>
        <string>start</string>
        <string>--desktop</string>
        <string>--config</string>
        <string>${configPath}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>Crashed</key>
        <true/>
    </dict>
    <key>StandardOutPath</key>
    <string>${homedir()}/.ronin/logs/ronin-desktop.log</string>
    <key>StandardErrorPath</key>
    <string>${homedir()}/.ronin/logs/ronin-desktop.error.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
</dict>
</plist>`;
}

/**
 * Generate Automator workflow bundle
 */
function generateWorkflowBundle(workflowPath: string, port: number): void {
  const workflowDir = join(workflowPath, "Send to Ronin.workflow");
  const contentsDir = join(workflowDir, "Contents");
  
  // Create directory structure
  mkdirSync(contentsDir, { recursive: true });
  
  // Write Info.plist
  const infoPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleIdentifier</key>
    <string>ai.ronin.send-to-ronin</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Send to Ronin</string>
    <key>CFBundlePackageType</key>
    <string>BNDL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright © 2025 Ronin</string>
    <key>NSServices</key>
    <array>
        <dict>
            <key>NSMenuItem</key>
            <dict>
                <key>default</key>
                <string>Send to Ronin</string>
            </dict>
            <key>NSMessage</key>
            <string>runWorkflowAsService</string>
            <key>NSRequiredContext</key>
            <dict/>
            <key>NSSendTypes</key>
            <array>
                <string>NSFilenamesPboardType</string>
            </array>
        </dict>
    </array>
</dict>
</plist>`;
  
  writeFileSync(join(workflowDir, "Info.plist"), infoPlist);
  
  // Write document.wflow (simplified - just calls our AppleScript)
  const documentWflow = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AMApplicationBuild</key>
    <string>523</string>
    <key>AMApplicationVersion</key>
    <string>2.10</string>
    <key>AMDocumentVersion</key>
    <string>2</string>
    <key>actions</key>
    <array>
        <dict>
            <key>action</key>
            <dict>
                <key>AMAccepts</key>
                <dict>
                    <key>Container</key>
                    <string>List</string>
                    <key>Optional</key>
                    <true/>
                    <key>Types</key>
                    <array>
                        <string>com.apple.cocoa.path</string>
                    </array>
                </dict>
                <key>AMActionVersion</key>
                <string>1.0.2</string>
                <key>AMApplication</key>
                <array>
                    <string>Automator</string>
                </array>
                <key>AMParameterProperties</key>
                <dict>
                    <key>source</key>
                    <dict/>
                </dict>
                <key>AMProvides</key>
                <dict>
                    <key>Container</key>
                    <string>List</string>
                    <key>Types</key>
                    <array>
                        <string>com.apple.cocoa.path</string>
                    </array>
                </dict>
                <key>ActionBundlePath</key>
                <string>/System/Library/Automator/Run AppleScript.action</string>
                <key>ActionName</key>
                <string>Run AppleScript</string>
                <key>ActionParameters</key>
                <dict>
                    <key>source</key>
                    <string>${generateQuickActionScript(port).replace(/</g, "&lt;").replace(/>/g, "&gt;")}</string>
                </dict>
                <key>BundleIdentifier</key>
                <string>com.apple.Automator.RunScript</string>
                <key>CFBundleVersion</key>
                <string>1.0.2</string>
                <key>CanShowSelectedItemsWhenRun</key>
                <true/>
                <key>CanShowWhenRun</key>
                <true/>
                <key>Category</key>
                <array>
                    <string>AMCategoryUtilities</string>
                </array>
                <key>Class Name</key>
                <string>RunScriptAction</string>
                <key>InputUUID</key>
                <string>INPUT_UUID</string>
                <key>Keywords</key>
                <array>
                    <string>Run</string>
                </array>
                <key>OutputUUID</key>
                <string>OUTPUT_UUID</string>
                <key>UUID</key>
                <string>ACTION_UUID</string>
                <key>UnlocalizedApplications</key>
                <array>
                    <string>Automator</string>
                </array>
                <key>arguments</key>
                <dict/>
                <key>conversionLabel</key>
                <integer>0</integer>
                <key>isViewed</key>
                <true/>
                <key>location</key>
                <string>0.5, 0.5</string>
                <key>namingDisplayFlags</key>
                <integer>0</integer>
            </dict>
        </dict>
    </array>
    <key>connectors</key>
    <dict/>
    <key>variables</key>
    <array>
        <dict>
            <key>UUID</key>
            <string>VARIABLE_UUID</string>
            <key>identifier</key>
            <string>inputPath</string>
            <key>name</key>
            <string>inputPath</string>
        </dict>
    </array>
    <key>workflowMetaData</key>
    <dict>
        <key>applicationBundleIDsByPath</key>
        <dict/>
        <key>applicationPaths</key>
        <array/>
        <key>inputTypeIdentifier</key>
        <string>com.apple.Automator.fileSystemObject</string>
        <key>outputTypeIdentifier</key>
        <string>com.apple.Automator.nothing</string>
        <key>presentationMode</key>
        <integer>15</integer>
        <key>processesInput</key>
        <integer>0</integer>
        <key>serviceInputTypeIdentifier</key>
        <string>com.apple.Automator.fileSystemObject</string>
        <key>serviceProcessesInput</key>
        <integer>1</integer>
        <key>systemImageName</key>
        <string>NSActionTemplate</string>
        <key>useAutomaticInputType</key>
        <integer>0</integer>
        <key>workflowTypeIdentifier</key>
        <string>com.apple.Automator.servicesMenu</string>
    </dict>
</dict>
</plist>`;
  
  writeFileSync(join(workflowDir, "document.wflow"), documentWflow);
}

/**
 * Install macOS Desktop Mode integrations
 */
export function install(options: InstallerOptions = {}): boolean {
  const port = options.bridgePort || DEFAULTS.bridgePort;
  const roninPath = process.env.RONIN_PATH || "ronin";
  
  console.log("🔧 Installing Ronin Desktop Mode for macOS...\n");
  
  try {
    // 1. Create Quick Action workflow
    const servicesDir = join(homedir(), "Library", "Services");
    const workflowDir = join(servicesDir, "Send to Ronin.workflow");
    
    if (existsSync(workflowDir)) {
      console.log("  ⚠️  Quick Action already exists, removing...");
      execSync(`rm -rf "${workflowDir}"`);
    }
    
    console.log("  📦 Creating Quick Action workflow...");
    generateWorkflowBundle(servicesDir, port);
    
    // 2. Create LaunchAgent
    const launchAgentsDir = join(homedir(), "Library", "LaunchAgents");
    const plistPath = join(launchAgentsDir, "ai.ronin.desktop.plist");
    const configPath = join(homedir(), ".ronin", "config.json");
    
    if (!existsSync(launchAgentsDir)) {
      mkdirSync(launchAgentsDir, { recursive: true });
    }
    
    // Ensure log directory exists
    const logDir = join(homedir(), ".ronin", "logs");
    if (!existsSync(logDir)) {
      mkdirSync(logDir, { recursive: true });
    }
    
    if (existsSync(plistPath)) {
      console.log("  ⚠️  LaunchAgent already exists, removing...");
      execSync(`launchctl unload "${plistPath}" 2>/dev/null || true`);
      unlinkSync(plistPath);
    }
    
    console.log("  📦 Creating LaunchAgent...");
    const plist = generateLaunchAgentPlist(roninPath, configPath);
    writeFileSync(plistPath, plist);
    
    // 3. Load the LaunchAgent
    console.log("  🚀 Loading LaunchAgent...");
    execSync(`launchctl load "${plistPath}"`);
    
    console.log("\n✅ Installation complete!");
    console.log("\n📋 What was installed:");
    console.log(`   • Quick Action: Right-click any file → Services → Send to Ronin`);
    console.log(`   • LaunchAgent: Ronin will auto-start with macOS`);
    console.log(`   • Bridge Port: ${port} (for OS communications)`);
    
    console.log("\n🔧 Next steps:");
    console.log("   1. Enable Desktop Mode: ronin config set desktop.enabled true");
    console.log("   2. Start Ronin: ronin start");
    console.log("   3. Right-click a file → Services → Send to Ronin");
    
    // 4. Install RoninTray for system tray
    console.log("\n📦 Installing RoninTray system tray application...");
    const trayInstalled = installRoninTray();
    
    if (!trayInstalled) {
      console.log("⚠️  RoninTray installation failed, but Desktop Mode is still functional");
    }
    
    return true;
  } catch (error) {
    console.error("\n❌ Installation failed:", error);
    return false;
  }
}

/**
 * Uninstall macOS Desktop Mode integrations
 */
export function uninstall(): boolean {
  console.log("🗑️  Uninstalling Ronin Desktop Mode...\n");
  
  try {
    // 1. Remove Quick Action
    const workflowDir = join(homedir(), "Library", "Services", "Send to Ronin.workflow");
    if (existsSync(workflowDir)) {
      console.log("  🗑️  Removing Quick Action...");
      execSync(`rm -rf "${workflowDir}"`);
    } else {
      console.log("  ℹ️  Quick Action not found");
    }
    
    // 2. Remove LaunchAgent
    const plistPath = join(homedir(), "Library", "LaunchAgents", "ai.ronin.desktop.plist");
    if (existsSync(plistPath)) {
      console.log("  🗑️  Removing LaunchAgent...");
      execSync(`launchctl unload "${plistPath}" 2>/dev/null || true`);
      unlinkSync(plistPath);
    } else {
      console.log("  ℹ️  LaunchAgent not found");
    }
    
    console.log("\n✅ Uninstallation complete!");
    return true;
  } catch (error) {
    console.error("\n❌ Uninstallation failed:", error);
    return false;
  }
}

/**
 * Get installation status
 */
export function getStatus(): InstallationStatus {
  const workflowPath = join(homedir(), "Library", "Services", "Send to Ronin.workflow");
  const plistPath = join(homedir(), "Library", "LaunchAgents", "ai.ronin.desktop.plist");
  
  return {
    quickActionInstalled: existsSync(workflowPath),
    launchAgentInstalled: existsSync(plistPath),
    desktopModeEnabled: false, // Would need to check config
    bridgePort: DEFAULTS.bridgePort,
  };
}

/**
 * Verify all installations are working
 */
export function verify(): boolean {
  console.log("🔍 Verifying Ronin Desktop Mode installation...\n");
  
  const status = getStatus();
  let allGood = true;
  
  // Check Quick Action
  if (status.quickActionInstalled) {
    console.log("  ✅ Quick Action installed");
  } else {
    console.log("  ❌ Quick Action not found");
    allGood = false;
  }
  
  // Check LaunchAgent
  if (status.launchAgentInstalled) {
    console.log("  ✅ LaunchAgent installed");
    
    // Check if it's loaded
    try {
      const result = execSync("launchctl list | grep ai.ronin.desktop", { encoding: "utf-8" });
      if (result.includes("ai.ronin.desktop")) {
        console.log("  ✅ LaunchAgent loaded");
      } else {
        console.log("  ⚠️  LaunchAgent installed but not loaded");
      }
    } catch {
      console.log("  ⚠️  LaunchAgent installed but not loaded");
    }
  } else {
    console.log("  ❌ LaunchAgent not found");
    allGood = false;
  }
  
  // Check Ronin CLI
  try {
    execSync("which ronin", { stdio: "pipe" });
    console.log("  ✅ Ronin CLI found");
  } catch {
    console.log("  ❌ Ronin CLI not found in PATH");
    allGood = false;
  }
  
  console.log("\n" + (allGood ? "✅ All checks passed!" : "⚠️  Some issues found"));
  
  return allGood;
}

/**
 * Reinstall (uninstall then install)
 */
export function reinstall(options: InstallerOptions = {}): boolean {
  console.log("🔄 Reinstalling Ronin Desktop Mode...\n");
  
  if (uninstall()) {
    return install(options);
  }
  
  return false;
}

/**
 * Generate LaunchAgent plist for daemon
 */
function generateDaemonPlist(roninPath: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ronin.daemon</string>
    <key>ProgramArguments</key>
    <array>
        <string>${roninPath}</string>
        <string>start</string>
        <string>--daemon</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${DAEMON_LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${DAEMON_LOG_PATH}</string>
    <key>WorkingDirectory</key>
    <string>${process.cwd()}</string>
</dict>
</plist>`;
}

/**
 * Install daemon as LaunchAgent
 */
export function installDaemon(roninPath?: string): boolean {
  try {
    const roninExecutable = roninPath || process.execPath;
    const plistContent = generateDaemonPlist(roninExecutable);
    
    // Ensure LaunchAgents directory exists
    const launchAgentsDir = join(homedir(), "Library", "LaunchAgents");
    if (!existsSync(launchAgentsDir)) {
      mkdirSync(launchAgentsDir, { recursive: true });
    }
    
    // Write plist file
    writeFileSync(DAEMON_PLIST_PATH, plistContent);
    
    // Load the LaunchAgent
    execSync(`launchctl load "${DAEMON_PLIST_PATH}"`, { stdio: "pipe" });
    
    console.log("✅ Daemon installed as LaunchAgent");
    console.log(`   Plist: ${DAEMON_PLIST_PATH}`);
    console.log(`   Logs: ${DAEMON_LOG_PATH}`);
    return true;
  } catch (error) {
    console.error("❌ Failed to install daemon:", error);
    return false;
  }
}

/**
 * Uninstall daemon LaunchAgent
 */
export function uninstallDaemon(): boolean {
  try {
    // Unload if loaded
    if (existsSync(DAEMON_PLIST_PATH)) {
      try {
        execSync(`launchctl unload "${DAEMON_PLIST_PATH}"`, { stdio: "pipe" });
      } catch {
        // May not be loaded, continue
      }
      
      // Remove plist file
      unlinkSync(DAEMON_PLIST_PATH);
    }
    
    console.log("✅ Daemon uninstalled");
    return true;
  } catch (error) {
    console.error("❌ Failed to uninstall daemon:", error);
    return false;
  }
}

/**
 * Install RoninTray system tray application
 */
export function installRoninTray(): boolean {
  try {
    const appDestination = "/Applications/RoninTray.app";
    
    // Get the embedded RoninTray.app from the Ronin installation
    const embeddedApp = join(process.cwd(), "RoninTray.app");
    
    console.log("📦 Installing RoninTray...");
    
    // Check if we have the embedded app
    if (!existsSync(embeddedApp)) {
      console.warn("⚠️  RoninTray.app not found in Ronin installation.");
      console.log("💡 RoninTray will be available in future releases.");
      console.log("   For now, you can access the dashboard at: http://localhost:17341/");
      return true; // Don't fail the installation
    }
    
    // Remove old version if it exists
    if (existsSync(appDestination)) {
      console.log("   Removing previous installation...");
      try {
        execSync(`rm -rf "${appDestination}"`);
      } catch {
        console.warn("⚠️  Could not remove old RoninTray installation");
      }
    }
    
    // Copy the app to Applications
    console.log("📦 Installing RoninTray.app to /Applications...");
    try {
      execSync(`cp -r "${embeddedApp}" "${appDestination}"`);
    } catch (error) {
      console.error("❌ Failed to install RoninTray.app");
      console.log("💡 You can install manually:");
      console.log(`    cp -r "${embeddedApp}" "${appDestination}"`);
      return true; // Don't fail installation
    }
    
    // Create LaunchAgent for RoninTray auto-start
    const trayLaunchAgentDir = join(homedir(), "Library", "LaunchAgents");
    if (!existsSync(trayLaunchAgentDir)) {
      mkdirSync(trayLaunchAgentDir, { recursive: true });
    }
    
    const trayLaunchAgentPath = join(trayLaunchAgentDir, "com.roninito.ronintray.plist");
    const trayLaunchAgent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.roninito.ronintray</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Applications/RoninTray.app/Contents/MacOS/RoninTray</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${homedir()}/.ronin/logs/ronintray.log</string>
    <key>StandardErrorPath</key>
    <string>${homedir()}/.ronin/logs/ronintray.error.log</string>
</dict>
</plist>`;
    
    writeFileSync(trayLaunchAgentPath, trayLaunchAgent);
    
    // Load the LaunchAgent
    try {
      execSync(`launchctl load "${trayLaunchAgentPath}"`, { stdio: "pipe" });
    } catch {
      execSync(`launchctl unload "${trayLaunchAgentPath}" 2>/dev/null; launchctl load "${trayLaunchAgentPath}"`, { stdio: "pipe" });
    }
    
    console.log("✅ RoninTray installed successfully");
    console.log(`   App: /Applications/RoninTray.app`);
    console.log(`   LaunchAgent: ${trayLaunchAgentPath}`);
    
    return true;
  } catch (error) {
    console.error("❌ Failed to install RoninTray:", error);
    return false;
  }
}
